### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by syntaxhacker** [lowweihong/university_ranking_scraper#1]
how to fix this ?

![image](https://user-images.githubusercontent.com/30970495/73136577-21c2fe80-4075-11ea-9e6a-d269dfbff8d3.png)

**Comment by lowweihong** [comment]
Hi @syntaxhacker Could you try to run the code on your local instead of google collab? It seems that US news blocked the access that is from google collab. :(

**Comment by syntaxhacker** [comment]
yeah it works fine on local machine :+1:
