### ISSUE TITLE
issue during run the code, asking for help

### ISSUE THREAD

**Issue by jihadkenani** [lowweihong/university_ranking_scraper#3]
Hello sir,
Thanks for your effort to explain the program of crawling university rank from us_news.
I would like to ask you a question about a problem that I met

Note: I am intermediate in python. 
I can’t run the program and saw that you put notes in the beginning .why?
I installed us_news correctly, however, it does not work.

I want to discuss this work with my colleagues. 
I would be grateful if you could save some time for a small online meeting to teach me how to handle this work. or maybe you can record a short video.
However, I sent already an email to you hoping for your reply soon.
 
Thank you in advance
![Image20230310233339](https://user-images.githubusercontent.com/93352550/224440794-be2895b4-9ad9-4570-ac1c-d2a045eb6af9.png)

**Comment by lowweihong** [comment]
Hi jihadkenan, I have fix the bug of the code, u can first uninstall and install again the repo
